# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarriel <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/02 19:07:57 by abarriel          #+#    #+#              #
#    Updated: 2016/11/02 19:07:59 by abarriel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRCS = ft_display_file

all:	$(NAME)

$(NAME) :
	gcc -Wall -Werror -Wextra ft_display_file.c ft.c -o ft_display_file
clean :
	rm -f ft_display_file.o
fclean :
	rm -f $(NAME)
re : fclean all
